language: node_js
node_js:
- "10"
- "12"
- "14"
cache:
  yarn: true
install:
  - yarn
script:
  - yarn build
  - yarn build:lkg
  - yarn cover
  - node lkg/bin/index
after_success:
  - yarn coveralls
